name: Python Tests with Allure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest

      - name: Set up Java (required for Allure CLI)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -xzf allure-2.27.0.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure

      - name: Run Pytest and collect Allure results
        run: |
          source venv/bin/activate
          python -m pytest --alluredir=Reports || true
          allure generate --clean --single-file -o Reports || true
        
        
      - name: Move single HTML report to docs
        run: |
          mkdir -p docs
          if [ -f Reports/index.html ]; then
            mv Reports/index.html docs/
          else
            echo "index.html not found, skipping move step"
          fi
        

      # - name: Run Pytest and collect Allure results
      #   run: |
      #     source venv/bin/activate
      #     python -m pytest --alluredir=Reports || true
      #     allure generate --single-file -o Reports || true

      # - name: Move single HTML report to docs
      #   run: |
      #     mkdir -p docs
      #     mv Reports/index.html docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: main
          keep_files: false
